"use client";

import { forwardRef } from "react";
import { cn } from "@/lib/utils";

interface ArtifactCardProps {
    mode: 'dream' | 'idea' | 'win' | 'thought';
    content: string;
    role: string | null;
    date: string;
    keywords?: string[];
}

const ArtifactCard = forwardRef<HTMLDivElement, ArtifactCardProps>(({ mode, content, role, date, keywords }, ref) => {

    const getTheme = () => {
        switch (mode) {
            case 'idea': return "from-yellow-500/20 to-orange-500/20 border-yellow-500/30";
            case 'win': return "from-emerald-500/20 to-teal-500/20 border-emerald-500/30";
            case 'thought': return "from-blue-500/20 to-indigo-500/20 border-blue-500/30";
            default: return "from-purple-500/20 to-pink-500/20 border-purple-500/30";
        }
    };

    const getIcon = () => {
        switch (mode) {
            case 'idea': return "⚡";
            case 'win': return "🏆";
            case 'thought': return "🧠";
            default: return "🌙";
        }
    };

    return (
        <div
            ref={ref}
            className={cn(
                "w-[600px] h-[800px] bg-black relative flex flex-col p-12 overflow-hidden",
                // We use a high quality gradient background
            )}
        >
            {/* Background Effects */}
            <div className={cn("absolute inset-0 bg-gradient-to-br", getTheme())} />
            <div className="absolute inset-0 bg-[url('/noise.png')] opacity-20 mix-blend-overlay" />

            {/* Branding Header */}
            <div className="relative z-10 flex justify-between items-center mb-16">
                <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-xl bg-white/10 backdrop-blur-md flex items-center justify-center text-xl border border-white/10">
                        {getIcon()}
                    </div>
                    <span className="text-xl font-bold tracking-widest text-white/90 uppercase">KOGITO</span>
                </div>
                <div className="text-sm font-mono text-white/40 tracking-widest">
                    {date}
                </div>
            </div>

            {/* Main Content Area */}
            <div className="relative z-10 flex-1 flex flex-col justify-center">

                {role && (
                    <div className="mb-6">
                        <span className="bg-white/10 text-white/90 px-4 py-1.5 rounded-full text-sm font-bold tracking-wider border border-white/20 uppercase">
                            {role}
                        </span>
                    </div>
                )}

                <h1 className="text-4xl md:text-5xl font-serif text-white leading-tight mb-8">
                    "{content}"
                </h1>

                <div className="flex flex-wrap gap-2 mt-4">
                    {keywords?.map(k => (
                        <span key={k} className="text-white/40 text-sm font-mono">#{k}</span>
                    ))}
                </div>
            </div>

            {/* Footer */}
            <div className="relative z-10 mt-16 pt-8 border-t border-white/10 flex justify-between items-end">
                <div>
                    <p className="text-white/60 text-sm font-medium">The OS for your Mind</p>
                </div>
                <div className="text-white/20 text-xs font-mono uppercase tracking-widest">
                    Generated by Kogito AI
                </div>
            </div>
        </div>
    );
});

ArtifactCard.displayName = "ArtifactCard";
export default ArtifactCard;
